import json
import os
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import torch
from PIL import Image
import ultralytics
from ultralytics.engine.results import Results


workspace = os.path.dirname(os.path.dirname(os.path.abspath(ultralytics.__file__)))
os.chdir(workspace)
print("set workspace:", workspace)


from data_engine_agent import Instance, Sample  # noqa: E402  pylint: disable=C0413


def to_ultralytics_results(self, img_source: str | None = None):
        """Convert this Sample to an ultralytics.engine.results.Results object and return it.

        Behavior:
        - Loads the image from im_file (optionally prefixed by img_source if provided).
        - Builds names mapping from instance texts (deduplicated in first-seen order).
        - Converts instance bboxes to xyxy and stacks [x1,y1,x2,y2, conf, cls] per row.
        - Returns a Results object with orig_img, path, names, boxes.

        Notes:
        - Instance.bbox can be [x1,y1,x2,y2] or [[x1,y1,x2,y2]]; both are handled.
        - If an instance has no conf set, defaults to 1.0.
        - Class ids are assigned by the index of the instance text in the names list.
        """
        # Resolve image path
        im_path = self.im_file
        if img_source is not None and not os.path.isabs(im_path):
            im_path = os.path.join(img_source, im_path)

        # Load image
        orig_img = np.array(Image.open(im_path).convert("RGB"))
        img_h, img_w = orig_img.shape[:2]

        # Build names mapping from instance texts (take first text per instance)
        unique_names = []
        for inst in self.instances:
            if inst.text is None or len(inst.text) == 0:
                cls_name = "unknown"
            else:
                cls_name = str(inst.text[0])
            if cls_name not in unique_names:
                unique_names.append(cls_name)
        names = {int(i): str(n) for i, n in enumerate(unique_names)}

        # Compose boxes tensor [x1,y1,x2,y2, conf, cls]
        rows = []
        for inst in self.instances:
            # bbox may be [x1,y1,x2,y2] or [[x1,y1,x2,y2]]; normalize to flat
            bbox = inst.bbox
            bbox_arr = np.asarray(bbox, dtype=np.float32)
            if bbox_arr.ndim == 2 and bbox_arr.size == 4:
                bbox_arr = bbox_arr.reshape(4)
            elif bbox_arr.ndim == 1 and bbox_arr.size == 4:
                pass
            else:
                # If bbox seems to be normalized xywh (length 4) but not in xyxy, try best-effort convert
                # Here we assume bbox is already xyxy as produced by load_from_yoloe_result.
                bbox_arr = bbox_arr.reshape(-1)
                if bbox_arr.size != 4:
                    # Skip malformed bbox
                    continue

            # Confidence
            if getattr(inst, 'conf', None) is not None and len(inst.conf) > 0:
                try:
                    conf = float(np.asarray(inst.conf).reshape(-1)[0])
                except Exception:
                    conf = 1.0
            else:
                conf = 1.0

            # Class id from names list
            cls_name = str(inst.text[0]) if (inst.text and len(inst.text) > 0) else "unknown"
            try:
                cls_id = float(unique_names.index(cls_name))
            except ValueError:
                # Fallback to last index if somehow unseen
                unique_names.append(cls_name)
                names[len(names)] = cls_name
                cls_id = float(len(unique_names) - 1)

            row = np.concatenate([bbox_arr.astype(np.float32), np.array([conf, cls_id], dtype=np.float32)])
            rows.append(row)

        if len(rows) == 0:
            boxes_tensor = torch.empty((0, 6), dtype=torch.float32)
        else:
            boxes_tensor = torch.from_numpy(np.vstack(rows).astype(np.float32))

        result = Results(
            orig_img=orig_img,
            path=im_path,
            names=names,
            boxes=boxes_tensor
        )
        if result.boxes is not None:
            # Avoid tracking metadata usage differences
            try:
                result.boxes.is_track = False
            except Exception:
                pass
        return result



def load_from_json(json_path: Path | str) -> Sample:
    """Load a `Sample` from a JSON file generated by the data engine."""

    def _ensure_sequence(value: Any) -> List[Any]:
        """Normalize single values to a list while leaving iterables intact."""

        if value is None:
            return []
        if isinstance(value, (list, tuple)):
            return list(value)
        return [value]



    json_path = Path(json_path)
    if not json_path.is_file():
        raise FileNotFoundError(f"Sample JSON not found: {json_path}")

    with json_path.open("r", encoding="utf-8") as handle:
        payload: Dict[str, Any] = json.load(handle)

    sample = Sample()
    sample.im_file = payload.get("im_file")
    sample.other_data = payload.get("other_data", {}) or {}
    sample.other_data.setdefault("_source_json", str(json_path))
    sample.instances = []
    sample.texts = []

    for instance_data in payload.get("instances", []):
        bbox = instance_data.get("bbox")
        if bbox is None:
            raise ValueError("Instance entry is missing required 'bbox' field")
        inst = Instance(bbox=bbox)

        texts = _ensure_sequence(instance_data.get("text"))
        confs = _ensure_sequence(instance_data.get("conf"))
        if texts:
            if confs and len(texts) != len(confs):
                raise ValueError("Text and confidence list must have the same length")
            confidences = [float(c) if c is not None else 0.0 for c in confs] if confs else [0.0] * len(texts)
            inst.set_text(texts, confidences)
            for text in texts:
                if text not in sample.texts:
                    sample.texts.append(text)

        embed = instance_data.get("embed")
        if embed is not None:
            inst.set_embed(embed)

        vp = instance_data.get("vp")
        if vp is not None:
            inst.set_vpe(np.array(vp))

        inst.other_data = instance_data.get("other_data") or {}
        sample.instances.append(inst)

    return sample








if __name__ == "__main__":
    pass

    # split="grounding_data_merged"

    # json_path = Path(f"/root/ultra_louis_work/runs/flickr_engine_buffer/{split}/2.json")

    # print("Loading sample from:", json_path)
    # sam=Sample()
    # sample=sam.load_from_grounding_label(json_path)

    # print(f"Loaded {len(sample.instances)} instances from {sample.im_file}")
    # output_path = Path(f"../visual_json_{split}/visual_img.jpg")
    # saved_path = visualize_sample(sample, output_path)
    # print(f"Saved visualization to {saved_path}")




    # split="merge_prediction"

    # json_path = Path(f"/root/ultra_louis_work/runs/flickr_engine_buffer/{split}/2.json")
    # sample = load_from_json(json_path)
    # print(f"Loaded {len(sample.instances)} instances from {sample.im_file}")
    # output_path = Path(f"../visual_json_{split}/visual_img.jpg")
    # saved_path = visualize_sample(sample, output_path)
    # print(f"Saved visualization to {saved_path}")
